{
    'name': 'Moneris Payment Acquirer (Hosted)',
    'version': '13.1.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Moneris Payment Acquirer (Hosted)',
    'description': """Moneris Payment Acquirer (Hosted)""",
    'author': "Syncoria Inc.",
    'website': "https://www.syncoria.com",
    'company': 'Syncoria Inc.',
    'maintainer': 'Syncoria Inc.',
    'depends': ['payment','sale','website_sale'],
    "external_dependencies": {"python": ['xmltodict']},
    'images': [
        'static/description/banner.png',
    ],
    'data': [
        'views/payment_moneris_templates.xml',
        'views/payment_views.xml',
        'data/moneris.xml',
        'views/response_status.xml',
    ],
    'price': 400,
    'currency': 'USD',
    'license': 'OPL-1',
    'support': "support@syncoria.com",
    'installable': True,
    'application': False,
    'auto_install': False,
    #'uninstall_hook': 'uninstall_hook',
}